### ISSUE TITLE
list doesn't reflect changes to array/object properties from the parent scope.

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-list#109]
Iron-list: http://jsbin.com/subuqi/1/edit?html,output

It works fine if you replace the iron-list with a dom-repeat http://jsbin.com/bejivu/edit?html,output

**Comment by kevinpschaaf** [comment]
Root caused to https://github.com/Polymer/polymer/blob/master/src/lib/template/templatizer.html#L243 not adding `notifyPath` API, or any related path handling capability to the template.

**Comment by kevinpschaaf** [comment]
Blocked on core issue https://github.com/Polymer/polymer/issues/2505.

The solution is non-trivial, and may cause us to rethink the templatizer design that allows the templatizer client (element that has the `Polymer.Templatizer` behavior, iron-list in this case) to be separate from the templatized template (in this case, the light-dom template passed to iron-list).

We may need to consider a breaking change to `iron-list` that would move to making the `<template>` itself a custom element, rather than passing a template to the custom element.

That is, moving from:

```html
<iron-list items="{{items}}">
  <template>...</template>
</iron-list>
```

to:

```html
<div style="overflow:auto;">
  <template is="iron-list" items="{{items}}">...</template>
</div>
```

We could supply a scroller/list container that provides the scrolling styling and possibly other value-added features, aka:

```html
<iron-scroller>
  <template is="iron-list" items="{{items}}">...</template>
<iron-scroller>
```

This needs to be weighed against any long-term needs for the Templatizer to be separable from the templatized template(s), for supporting things like polymorphic templates.

**Comment by niflostancu** [comment]
I really like the idea of template instances being linked to both the parent element that defines it and  the Templatizer client that uses it.

It brings new possibilities of customizability for Polymer elements.
For example, I'm currently working on a data table element that needs to be able to render rich cells for certain columns (e.g. action buttons / custom HTML code). 
This can be accomplished by the user of the element providing templates for each column (which may need to have event listeners and data bindings on the parent/user element) and the table element will use them for stamping the cell contents.

**Comment by kevinpschaaf** [comment]
For now, we went with a low-impact fix to just make it work, and preserves the ability to have Templatizer client and templatized template separate, as in the current iron-list implementation.

@blasten https://github.com/Polymer/polymer/issues/2505 is now resolved; can you confirm in `iron-list` and close?  Thanks.

**Comment by blasten** [comment]
@kevinpschaaf I can confirm that this bug has been fixed :)
http://jsbin.com/bejivu/edit?html,output \cc @sjmiles
