### ISSUE TITLE
Item dynamic height changes are not properly recalculated (Expand/Collapse)

### ISSUE THREAD

**Issue by mathieuxxxx** [PolymerElements/iron-list#13]
Hi,

I tried filling the iron-list with expandable items. (45px when collapsed, 345px when expanded)

When I expand an item, it overlaps the items below instead of pushing them further. 

Only when I scroll, then the items below are getting pushed further.

Also, when one of the item is expanded, I start having white spaces on bottom and top when scrolling.

Thanks

**Comment by blasten** [comment]
This was identified as a potential issue that needs an elegant solution. 
Q: do you know how the expandable item is changing its height? Is it a CSS transition on height or just JavaScript? Also, do you have a way to keep the state of the item (expanded/collapsed)? 

If you call `list._refreshAll()` after the item changed its height, the items should render properly in the right position. This is not a final solution, but it gives you an idea of how to work around it.

**Comment by tasosno1** [comment]
Are you appending <code>html</code> Data to the item dynamically that it expands  or do you just change the height for that item .

Appending some <code>html</code> expands an item ok as i'm doing that for an App

Changing the height for an item does not push other items below because (i presume) the list has got an overall height set already and that needs to be recalculated again  by doing a refresh.

Saying that when you re-size the browser you will notice it does an update/refresh your items should look ok.

Try this method and see if it helps

Onclick to expand >

<code>var firstVisible = document.getElementById("iron-list-id").firstVisibleIndex;</code>
<code>document.getElementById("ron-list-id").scrollToIndex(firstVisible);</code>

That gets the top most item in view index id (i.e. the item)
And scrolls to it.

So im not sure if that would work for you bu try it anyway.

If the top item is in half view i.e half of it is visible you may see a jump but if your items are 45px heiigh it wont be much.

**Comment by ebidel** [comment]
Seeing this too on chromestatus.com. Current workaround is to call `list._update()` after you click a feature panel. Feature panels are expanded by changing their css height.

https://github.com/GoogleChrome/chromium-dashboard/commit/d7df788ce167ab140f3d3e87c5050bf67befa78c#diff-48bf61fdf81b40310a82e557f4ac9bb0R230

**Comment by blasten** [comment]
`updateSizeForItem ` has landed in v1.1.3 https://github.com/PolymerElements/iron-list/releases/tag/v1.1.3
