### ISSUE TITLE
Can't nest iron-lists

### ISSUE THREAD

**Issue by ErikGrimes** [PolymerElements/iron-list#161]
Currently nesting lists doesn't work. For example, if you do this:

```
<iron-list items="{{items}}">
      <template>
        <div>
          outer item
        </div>
        <iron-list items="{{items}}">
          <template>
            <div>inner item</div>
          </template>
        </iron-list>
      </template>
    </iron-list>
```

you end up with two lists written on top of each other instead of a list of lists.

**Comment by blasten** [comment]
This is a limitation. It seems like you want to somehow group the data. The list doesn't have this feature yet, but you can still build something on top of the current list if you manage the relation between the outer item and the inner items.

**Comment by ErikGrimes** [comment]
I was just provided a simple example of the issue.  My model is a tree structure.  In some cases it might have 30 nodes at depth 1 with no children or it might have 10 nodes at depth 1 with 30 children each. Inbox with it's nested lists is sort of what I have in mind.  My case is a bit more complicated in that the tree can have arbitrary depth.  Would you explain a bit how I might manage the relationships between a parent list's items and its child list's items?

**Comment by enlight** [comment]
@ErikGrimes I recently started implementing a directory tree view ([code](https://github.com/debugworkbench/hydragon/blob/40c3c62c7b4ef402ce1c0fbb3a1c22aa0640cc20/src/renderer-process/elements/tree-view/directory-tree-view.ts)/[template](https://github.com/debugworkbench/hydragon/blob/40c3c62c7b4ef402ce1c0fbb3a1c22aa0640cc20/src/renderer-process/elements/tree-view/directory-tree-view.html)) that uses a single `iron-list` to display the directory hierarchy. The way it works is there's a [behavior](https://github.com/debugworkbench/hydragon/blob/40c3c62c7b4ef402ce1c0fbb3a1c22aa0640cc20/src/renderer-process/elements/tree-view/tree-view.ts) that takes a tree model and flattens it out into a one dimensional array of items, the directory tree view element then binds the array to an `iron-list`, and each item in the list is indented according to it's level in the tree. The flat array of items is updated as directories are expanded/collapsed, and the `iron-list` automatically updates due to the binding. Flattening a tree out into an array is a relatively straightforward exercise, keeping the array updated as the tree changes can be a bit tricky though (I haven't accounted for all the possibilities in my implementation yet).
