### ISSUE TITLE
iron-list doesn't appear to be observing array changes

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#193]
I recently ran into trouble with `value$=` data bindings in iron-list, I wasn't able to replicate that exact issue but it appears as if iron-list isn't observing array change notification declared using computed bindings or observers.  I've setup [examples of both](http://jsbin.com/homoqe/13/edit?html,output) and if you try to delete a record (which utilizes `this.splice`), iron-list will not update.

**Comment by indolering** [comment]
I would think that this is a p0 issue given that this blocks updating values to iron-list elements and essentially breaks data-binding.

**Comment by blasten** [comment]
@indolering this one does work: http://jsbin.com/qasahupapi/1/edit?html,output  iron-list currently doesn't support array filtering in the same way dom-repeat does. That feature is in the backlog and we do want to fully support it. It's just a matter of priorities. 

Things to keep in mind:
* Observe to `items.*` to get notification for splices.
* If the array is mutated without using the Polymer's mutation API, the only way to reflect the changes is to create a copy of the array. That's why you see the `array.slice`. 

Also, this a temporary solution. Generally speaking calling `array.slice` is just hack here.

**Comment by indolering** [comment]
Something screwy is still going on in my actual codebase, but this appears to fix the majority of issues.

**Comment by blasten** [comment]
good2know
