### ISSUE TITLE
scrollToIndex doesn't scroll correctly when using an external scroll target

### ISSUE THREAD

**Issue by WrinklyNinja** [PolymerElements/iron-list#196]
I've got an `<iron-list>` with a preceding sibling element, and which uses its parent as its scroll target, i.e.

```
<div id="container">
  <paper-material>Foo</paper-material>
  <iron-list scroll-target="container">
    <template>
      <paper-material>[[item]]</paper-material>
    </template>
  </iron-list>
</div>
```

If I use `scrollToIndex()`, the list scrolls to the wrong position, seemingly not taking into account the offset height of the element that precedes it. If I don't set an external scroll target, `scrollToIndex()` works as expected.

**Comment by frankiefu** [comment]
Yeah this is a bug in `iron-list` which doesn't account for the offset height of the element that precedes it.  Right now `iron-list` only uses the `padding-top` value of the `scroll target` to get the [offset](https://github.com/PolymerElements/iron-list/blob/v1.2.3/iron-list.html#L607).  So one hacky workaround is to pass that offset information to `iron-list` by setting `padding-top` and re-adjust it back using negative `margin-top`, e.g.
```
<div id="container" style="padding-top: 100px; margin-top: -100px;">
  <paper-material style="height: 100px;">Foo</paper-material>      
  <iron-list scroll-target="container">
    <template>
      <paper-material>[[item]]</paper-material>
    </template>
  </iron-list>
</div>
```

This solution is hacky and not ideal.  So we should come up with a better way to support this.

**Comment by WrinklyNinja** [comment]
I've found that simply replacing the `parseInt(window.getComputedStyle(this)['padding-top'], 10)` in `updateViewportBoundaries()` with `this.offsetTop` fixes the issue - I'd submit a PR, but I'm having trouble getting WCT set up to write a test for it...

**Comment by isaldarriaga** [comment]
This is the workaround i made on iron-list._itemsChanged function

//        if (this._scrollTop > this._scrollerPaddingTop) {
//          this._resetScrollPosition(0);
//        }

when lazy loading items when reaching the iron-list's bottom, _scrollTop is always way bigger than the _scrollerPaddingTop, because it represents the current scroll position. So the condition is always true. I cannot understand why resetting the position to the top is actually needed when updating items. this code breaks the UX.

This is the scenario (with an external scroll target): an iron-list without padding positioned below the app-toolbar + iron-tabs. the margin-top of the list matches the iron-tabs height. the scroll target is set to the header's scroll target (i.e. the html object).

Now the iron-list grows correctly.

**Comment by keanulee** [comment]
This should be fixed by #368

**Comment by WrinklyNinja** [comment]
Yep, confirmed fixed, thanks.

**Comment by yairopro** [comment]
The problem doesn't seem to me to be fixed.
[Here's a JSBin](http://jsbin.com/qiwiwojixo/edit?html,output) which show an iron-list of 50 items, and some controls at the bottom of the window, to jump at the wished index, using scrollToIndex method on the iron-list.
You'll be able to see that the header isn't taken into account as offset. Remove it, and the scroll works just fine.

**Comment by Westbrook** [comment]
@yairopro have you tested out the `scroll-offset` property?  A la: http://jsbin.com/gafonasuze/edit?html,output From the docs: 

> This property is useful when an external scrolling element is used and there's some offset between the scrolling element and the list. For example: a header is placed above the list.

**Comment by yairopro** [comment]
@Westbrook Thanks!!
