### ISSUE TITLE
Styling issue with iron-list elements requiring an explicit call to updateStyles()

### ISSUE THREAD

**Issue by rictic** [PolymerElements/iron-list#272]
> This bug has been moved into github from an internal bug tracker.
### Description

We have an iron-list with iron-icons which are sized by a css rule using --iron-icon-height/width. The styles are not consistently automatically applied. They correct themselves when updateStyles is manually called.
### Expected outcome

Items in iron-list should be styled correctly without an explicit call to `updateStyles`.
### Actual outcome

The new styles aren't applied until `updateStyles` is called.
### Live Demo

http://jsbin.com/baqajumesa/1/edit?html,output

**Comment by blasten** [comment]
This is unfortunately a limitation of the custom properties shim. Another way you can get the same behavior without calling `updateStyles` is to have multiple icons and toggle their `hidden` attribute to show/hide the icons. A little inefficient, but it wouldn't require `updateStyles`.

**Comment by peteblois** [comment]
Is there a recommended pattern to toggle the `hidden` attribute for freshly created iron-list items?

It's also quite odd that the behavior here is inconsistent- it's only occasionally that `updateStyles` needs to be called manually. We're still trying to understand what these circumstances are since it appears to reproduce in other components as well.

**Comment by blasten** [comment]
Every time the specificity of a selector _that defines custom properties_ changed, the shim needs to be notified so it can recalculate styles for the elements that consume those custom properties.  That is, said you change the class of an element _(already in the DOM)_ such that new custom properties match that element, you would need to call `updateStyles`.  However, if you add the class before appending the element to the DOM and use `Polymer.dom(parent).appendChild`, you wouldn't need to call `updateStyles` because `Polymer.dom.appendChild` will do it for you. In the iron-list case, the elements are virtualized. That is, the elements are only appended once, so if you change the selectors, the shim won't be able to catch those updates.

> Is there a recommended pattern to toggle the hidden attribute for freshly created iron-list items? 

How many different items do you have?

**Comment by peteblois** [comment]
In our scenario, there are only ~10 items in the list visible at a time. It sounds like you're recommending that `updateStyles` is called each time iron-list updates an element. I'm not sure how to get notified that it needs to be updated from iron-list.

Regarding `Polymer.dom.appendChild`- how does this differ from standard appendChild? We occasionally use Polymer elements for providing material design in non-polymer templating scenarios (Soy). For the most part it appears to work.

**Comment by blasten** [comment]
In general, it's better to avoid calling `updateStyles` too often, so you may want to toggle the hidden attribute. e.g. 

```html
<iron-list>
  <template>
    <div>
      <x-elem1 hidden$="[[_shouldHide('x-elem1', item)]]"></x-elem1>
      <x-elem2 hidden$="[[_shouldHide('x-elem2', item)]]"></x-elem2>
      <x-elem3 hidden$="[[_shouldHide('x-elem3', item)]]"></x-elem3>
    </div>
  </template>
</iron-list>
```

```js
 _shouldHide: function(elem, item) {
  // your logic
   return true;
}
```
