### ISSUE TITLE
Iron-list misses changes to items array

### ISSUE THREAD

**Issue by ronnyroeller** [PolymerElements/iron-list#279]
### Description
Changes to the `items` array that happen when the `iron-list` is invisible (e.g. in `dom-if`) aren't reflected when the list becomes again visible.

`IronList._render()` only applies changes if the list is visible (`_isVisible`), which makes a lot of sense to avoid unnecessary updates. But the changes are not applied once the list becomes visible.

Workaround: explicitly fire `iron-resize` whenever the list becomes again visible (and the data might have changed).

### Expected outcome

`iron-list` automatically re-renders when it becomes visible and if there were data changes.

### Actual outcome

`iron-list` is out of sync with the underlying data.

### Live Demo
https://jsbin.com/giquyajivi/3/edit?html,output

### Steps to reproduce

0. Open live example: https://jsbin.com/giquyajivi/3/edit?html,output

1. Hide list

2. Add item

3. Show list => New item is not visible

4. Force refresh via `iron-resize` => New item appears

**Comment by blasten** [comment]
That is the expected behavior. Visibility changes must be notified by the parent element by implementing `iron-resizable-behavior` which fires the `iron-resize` event. `iron-list` is different than `dom-repeat` in that iron-list lay outs the items in a list or grid fashion. That operation requires to measure the size of the content, thus it can only be if the content is rendered. In the future, as browser vendors expose native visibility observers to DOM Elements, we could move away from the current approach and do that automatically for you!
