### ISSUE TITLE
No possibilities to set a  grid with "aspect ratio" 

### ISSUE THREAD

**Issue by herbalizer404** [PolymerElements/iron-list#298]
### Description

I'm expecting to convert my app-grid to an Iron-list with infinte scroll effect. But my actual grid has an aspect ratio property to have a perfect responsive  render, but the fact that i need to set fixed height and width dont allow me to have the render i need. 
### Expected outcome

Iron-list grid with item that fully fill the parent div.
### Actual outcome

Not really responsive, items have fixed size.
### Live Demo

This is my actual grid. And i want to reproduce that with Iron list:
 http://polymer.les-eaters.fr/view1

**Comment by Westbrook** [comment]
As long as your design will continue as it is now with matched heights, you can manage this by using % to set the width of the holder rather than px to set the width of the item:

```
<style>
.item-holder {
width: 33%;
}
.item {
width: 100%;
}
</style>
<iron-list>
<template>
    <div class="item-holder">
        <div class="item">
            <h1>[[item.name]]</h1>
        </div>
    </div>
</template>
</iron-list>
```

And then all of your rows with have a full three items to matter the width of your page. Then you can play with things like `iron-media-query` and the like to make that more dynamic to your needs.

**Comment by blasten** [comment]
@herbalizer404 you could also use the `padding-top` trick. Use [this](https://css-tricks.com/snippets/sass/maintain-aspect-ratio-mixin/) for reference.
