### ISSUE TITLE
iron-list should yield control while stamping offscreen items

### ISSUE THREAD

**Issue by tgsergeant** [PolymerElements/iron-list#301]
### Description
When adding items to an iron-list, the list will prioritise stamping the first page worth of content, and then [yield to the next frame](https://github.com/PolymerElements/iron-list/blob/9de0830fa506d979eecdd3ae509b0c505dc25036/iron-list.html#L970) before it starts backfilling additional pages of content.

However, backfilling those pages will still block everything for the time it takes to render a page worth of items. This means that even after the first page of items is visible, the page is slow and janky until offscreen content has finished rendering.

### Expected outcome

The page should be interactive while offscreen content is stamped

### Actual outcome

The iron-list has two long frames which cause the page to be janky after first paint.

### Live Demo

This issue is visible in chrome://history on latest Chrome Canary or Dev channel. Here's a sample timeline trace:

![gqsofxpt9of](https://cloud.githubusercontent.com/assets/745035/17952619/9c7aefc4-6aaf-11e6-9d3d-186e6cf02382.png)

First paint occurs after the first block of work in that trace. Following that, there are two long frames after first paint while the iron-list backfills items. This is on a 1080p screen on a top-end desktop computer -- the frames can be considerably longer with larger screens or on a less performant machine. Even if we were able to aggressively optimise our list items to stamp 2-3x faster, it would still be difficult for us to hit RAIL metrics.

Ideally, the iron-list would instead yield control while stamping these offscreen items, stamping in small chunks rather than a whole page at a time. This would allow the user to interact with visible items during this time.

Additionally, it would be great if there was an event that fired after the iron-list was completely finished stamping offscreen items. This would allow us to add a performance metric to gather some real-world data about load performance, and also to schedule work after the list has finished.

Cc: @blasten @samuelli @danbeam

**Comment by blasten** [comment]
I think we can do better there. cc @kevinpschaaf

**Comment by blasten** [comment]
A few things that can be improved:

1. As of now, the pool is increased incrementally 1 by 1. That strategy causes linear style recalc, but I think increasing the pool by 1.5x the current size, would probably create more DOM, but it would balance the overall cost a little better. Also, the 1.5x strategy could yield on every pass.

2. In history, the items have fixed size. Because of that, there isn't really a need for measurement. Instead, the list could have a property (of type Function) that passes a DOM node (for the physical item)  and the item instance. e.g.  the default value for such a property could be: `function(node, item) { return  item.offsetHeight; }`, but now history could do something like `function(node, item) { return  64; }`. That would prevent all the style recalcs.

3. +1 on firing the event.

**Comment by samuelli** [comment]
When increasing the pool, a single style recalc isn't particularly expensive. The pool can easily then estimate how many are required to fill the remaining space based on that single (or maybe 2) calculated size. That way an extra property wouldn't be required.

Yield should be `performance.now()` based, yielding every 50ms as per RAIL. Or perhaps `requestIdleCallback()` should be used, stamping only when there are idle frames. Not sure how this would affect scrolling though.

**Comment by blasten** [comment]
> Yield should be performance.now() based, yielding every 50ms as per RAIL.  

+1

**Comment by blasten** [comment]
@tgsergeant @samuelli @danbeam tagged `v1.3.9`

**Comment by tgsergeant** [comment]
Thanks very much!
