### ISSUE TITLE
Issue with iron-list and Polymer 2.0

### ISSUE THREAD

**Issue by Alos** [PolymerElements/iron-list#353]
### Description

I have a similar issue to #74. When using `polymerelements/iron-list#^1.3.14` with Polymer 2.0-Preview I get a `Uncaught TypeError: this.$.selector.clearSelection is not a function(…)`

I've been looking at the problem and it happens on line 1591 on the `clearSelection` function. It tries to call clearSelection on a `array-selector` element. I've looked and the element implemented in polymer.html contains this method. Not sure why at runtime it does not (I'm still a Polymer newb).  

Also, not sure if related but the element I'm using the iron-list on is using the new class based Polymer Elements. 

### Expected outcome

A nice list with a bunch of items.

### Actual outcome

Exception on the console.

### Live Demo

Can't do those from work :(

### Steps to reproduce

1. Put an `iron-list` element in the page.
2. Use polymer-2.0-preview.

### Browsers Affected

- [x] Chrome

**Comment by blasten** [comment]
This issue is blocked on https://github.com/Polymer/polymer/issues/4154

**Comment by mbana** [comment]
i too am getting errors, although i am not sure if it is a coding error on my part or not.
my setup is polymer 2.0-preview, and i am using app-drawer-layout etc.

I guess the problem might be due to elements that can potentionally hide themselves, and possibly appending something to the list when the `iron-list` is in a hidden state. not sure i'm just guessing. basically, what's possibly happening is something like:

1. `app-drawer` x 2, both of which have an `iron-list` element within themselves.
2. when the elements are hidden append to their backing store --- the list.
3. i get a dead-lock or some undefinied behaviour as mentioned in https://github.com/PolymerElements/iron-list/issues/374.

i repeat, this is just a guess. i note however that the docs say to fire an resize event when this does happen but i think `<app-layout-*>` already do this? looking at the stack shows they do.

anywho, folks, examples from the core team would be wonderful :)

**Comment by keanulee** [comment]
This issue should be fixed now.
