### ISSUE TITLE
"Demo and API Docs" link on webcomponents.org does not lead to demos and 

### ISSUE THREAD

**Issue by sebs** [PolymerElements/iron-list#528]
### Expected outcome

Clicking on "Demo and API Docs" actually leads to api docs

### Actual outcome

Leads to the same page again. 

### Live Demo

* https://www.webcomponents.org/element/PolymerElements/iron-list

### Steps to reproduce

1. Goto: https://www.webcomponents.org/element/PolymerElements/iron-list
2. Click "Demo and Api Docs" 
3. No Demo 

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by keanulee** [comment]
The link, which is from the README, points to https://elements.polymer-project.org/elements/iron-list, and webcomponents.org just uses the README. webcomponents.org hasn't been displaying the link to the iron-list demos since [v2.0.14](https://www.webcomponents.org/element/PolymerElements/iron-list/v2.0.14). @samuelli Any ideas why?

**Comment by sebs** [comment]
Any idea when this is getting fixed? Any maybe the other 500 iron-* and paper-* elements get checked as well?

**Comment by Westbrook** [comment]
Does webcomponents.org use `polymer analyze` under the covers? I’ve had to update my `polymer.json` files to make the run on that actually build the `analysis.json` correctly and there doesn’t seem to be one in this project. Could that be the source of this issue?

**Comment by sebs** [comment]
What about, like the rest of the NODE.js world on NPM js, you provide REAL links to the real docs and do not send me off to some google search? Just to fix the problem at hand and not webcomponents.org? I can do the PR myself, but I need to know where the demo is located (which the docs of iron-list do not state, because it relies on a working webcomponents.org).

**Comment by keanulee** [comment]
The [NPM page for iron-list](https://www.npmjs.com/package/@polymer/iron-list) does show the README, but it doesn't have the properties/methods API docs that were [missing since v2.0.14](https://www.webcomponents.org/element/PolymerElements/iron-list/v2.0.14/elements/iron-list). PR on the README would work (and be much appreciated) as it already has links to working demos on JSBin.

**Comment by samuelli** [comment]
@keanulee docs are fixed now. README is still untouched

**Comment by keanulee** [comment]
Removed link from README in master

**Comment by sebs** [comment]
ORLY? Removed the link? Thanks
