### ISSUE TITLE
JSBIN links in docs are not working anymore

### ISSUE THREAD

**Issue by sebs** [PolymerElements/iron-list#529]
Clicking on on the JSBIn links in the Readme leads to broken demos. Polymer breaks ;)

**Comment by keanulee** [comment]
New breaking versions of polymer and webcomponentsjs were released, and the JS Bin demos pulled the latest releases from polygit so they also broke. They can be fixed by specifying the GitHub branches to use to polygit.

Replace:
```html
  <base href="https://polygit.org/components/">
```

with:
```html
  <base href="https://polygit.org/polymer+:2.x/webcomponentsjs+:v1/components/">
```

For example: https://jsbin.com/waxoxef/edit?html,output

I will update the links in the documentation soon.

**Comment by keanulee** [comment]
All 3 linked JS Bin demos have been updated.
