### ISSUE TITLE
Container height is not set properly when iron-list is in flexbox container

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-list#73]
My iron-list is sized inside a flex parent. So no explicit height but sized. The wrapper element is getting set to the full height of the scroll container (`height: 28382px` in the screenshot) instead of the height of the physical viewport. This causes the list not to regenerate on scroll.

<img width="1239" alt="screen shot 2015-08-22 at 10 15 55 am" src="https://cloud.githubusercontent.com/assets/238208/9425066/ad1b064a-48b7-11e5-9224-3820f9e775a6.png">

My current workaround is to set the height of the list on attached:

    attached: function() {
      this.$.ironlist.style.height = Polymer.dom(this).node.clientHeight + 'px';
    },

**Comment by blasten** [comment]
@ebidel That could happen if: 
*  iron-list is inside a paper-scroll-header-panel.
*  If iron-list doesn't have a explicit height and at least one of these is missing:
  1. The CSS flex property in iron-list:  e.g. `flex: 1 1`;  (class `flex`, mixin:  `@apply(--layout-flex);`)
  2.  iron-list's parent should have: `flex-direction: column;`  and  `display: flex;`. (classes `vertical layout`, mixin `@apply(--layout-vertical`))

**Comment by ebidel** [comment]
I was mistaken. The parent itself isn't a flex box container, but it's in other containers that are flex containers:

```
<div style="display:flex;flex: 1 0 0;">
  
<section style="display:flex;overflow: hidden">
  <nav></nav>
  <chromedash-features style="flex: 1 0 0;"></chromedash-features>
</section> 
  
</div>



<chromedash-features>
  #shadow-root
  <ul style="transform: translateZ(0);">
    <iron-list>
      <template>
        <li></li>
        ....
      </template>
    </iron-list>
  </ul>
</chromedash-features>
```

**Comment by m4b** [comment]
I have a very similar use case ([silicon-instructions](http://github.com/m4b/silicon-instructions)), and I'm having trouble getting iron-list to behave correctly with flexboxes.

So currently I have something like:

```html
<code id="code">
      <iron-list id="list" items="[[instructions]]" as="inst">
        <template>
          <silicon-instruction instruction="[[inst]]"></silicon-instruction>
        </template>
      </iron-list>
</code>
```

Ideally, I have a flexbox with `flex-direction: column` which fills up the entirely of the viewport, and inside of that is either a `<div>` or `<silicon-instruction>` which is flexed, but also overflow scrolls the `<iron-list>` content.

I think this is a common enough use case (flexing the full height of the viewport, and `overflow: scroll` for the list contents) that you're going to get more issues like this or questions posed other places, etc.

I'm still unable to get it to behave in the manner described above; the closest I get is @ebidel's solution for setting the height on attached, but this is very brittle, it'd need to be done on window resize, etc.

So going forward, it might be useful in the docs (or elsewhere) if there were a "prescribed method" for embedding `<iron-list>` in flexboxes so that they behave in the way I think we intuitively want them to behave - to flex as much as we specify, and scroll the rest of the list content inside.

**Comment by ebidel** [comment]
Perhaps this is some kind of race condition where the flex container doesn't have layout before iron-list does its setup calculations?

**Comment by blasten** [comment]
@ebidel are you using Polymer 1.1.0?

**Comment by ebidel** [comment]
Yea 1.1.1 is what's live on https://www.chromestatus.com/features atm.

**Comment by blasten** [comment]
Here's an example:  http://jsbin.com/nepeso/edit?html,output  I forgot to mention that you also need to add `fit` to the container or explicitly set the height.

**Comment by m4b** [comment]
@blasten: thanks for the jsbin, this is a good talking point!

So I've edited it slightly for what I think would be a common UI scenario:

http://jsbin.com/wanapuzoza/edit?html,console,output

essentially, the UI below the toolbar consists of a right and left half, in a horizontal flexbox.

In the left box (and the right too if we want) would be a vertical layout which expands the size of the visible screen, and scrolls after that (like your unmodified example).

Ideally they'd share half the space horizontally, and take up full height both, which a simple flexbox setup would allow; but because the `fit` class sets the iron-list div to absolute, it becomes problematic.

If you tweak around with the parameters it behaves in various unsuitable manners; I'm not sure what the solution is, but I'm also not a CSS-foo-master :)

Lastly, I have noticed some more rendering issues requiring firing `resize` on the list after it's laid out when using flexboxes; I'm not sure if it's related to this problem, and I will probably just raise another issue with an example, etc.

Anyway, this might be off topic with the original issue, so I'll leave it at that.

**Comment by ebidel** [comment]
@blasten, `class="fit vertical layout"` works great for me. Thanks.

**Comment by blasten** [comment]
@m4b http://jsbin.com/laqeve/edit?html,output The key point is that at least one ancestor of iron-list must explicitly define its own height. If no ancestor has a fixed height, then that will be equivalent to say `height: auto;`  As you pointed out, having a fixed height is problematic when you resize the window, that's when the class `fit` comes in.  An element with the class `fit` will always have the size of its immediate positioned ancestor. so when the element using `fit` is the first positioned element, then it will have the same width and height of the viewport.   The class `fit` is basically:

```css
.fit {
  position: absolute;
  top:0;
  left:0;
  right:0;
  bottom:0;
}
```
Now that I have an element that has a fixed size, I can use flexbox to lay out the content.
So again:

Example 1: A right drawer:
```
. body
.. div class= "fit horizontal layout"
... div class= "vertical layout flex"
.... paper-toolbar
.... iron-list class="flex"
... div class="right-drawer" style="width: 100px;" 
```

Example 2:  A toolbar on top.

```
. body
.. div class= "fit vertical layout"
... paper-toolbar
... iron-list class="flex"
```


Example 3:  A full screen list
```
. body
.. iron-list class="fit"
```

**Comment by m4b** [comment]
@blasten: thanks for being patient !  So I finally got it working, after looking at the source of the `chromium-featurelist`, and tinkering around.

My guess is this question is going to come up a lot as `<iron-list>` gets integrated into other projects and people want maximum style flexibility.  The jsbin's are a good reference, or even a static example or short article explaining what you said above and some of the other points in this issue would be a great resource to point people at I think.

**Comment by blasten** [comment]
+1

**Comment by dtruffaut** [comment]
@blasten 

Your precisions MUST be linked to the iron-list documentation.

Otherwise people will search for hours !

**Comment by blasten** [comment]
@dtruffaut take a look at https://github.com/PolymerElements/iron-list/pull/299 and let me know if it helps. ty!

**Comment by dtruffaut** [comment]
Sure it does ! :+1:

**Comment by zbzdwzz** [comment]
Have a question for this. Based one #299, the iron-list should be sized if one of the following is satisfied:
1. set a height for the "height" property in the style
2. the parent element is set to be a flex box container (display: flex; flex-direction: column), and the iron-list style has "flex: 1 1" (or other layout means)
3. inside a parent element which satisfies 1 or 2

however, it seems like even if the iron-list satisfies 2, a height is required in the parent element (flex box container). Adding "fit" class into the parent element of iron-list means that we make the flex box container have the "height" of flex-box container's ancestor. I do not know if I understand the discussion above correctly, or if I misunderstood #299.
