### ISSUE TITLE
🍞 iron-list overlapping position bug 🐛

### ISSUE THREAD

**Issue by samccone** [PolymerElements/iron-list#96]
I have a fairly simple iron-list :pencil2: , i have a height defined :straight_ruler:  for each element as well as for the container element, however I am running into an issue with elements overlapping :cold_sweat: 

![screen shot 2015-09-15 at 12 14 59 pm](https://cloud.githubusercontent.com/assets/883126/9887255/8675ee16-5ba3-11e5-87ec-266f6a7c4a30.png)

![screen shot 2015-09-15 at 12 15 27 pm](https://cloud.githubusercontent.com/assets/883126/9887253/865ad572-5ba3-11e5-8654-7160a1082b03.png)

![screen shot 2015-09-15 at 12 15 12 pm](https://cloud.githubusercontent.com/assets/883126/9887254/866f7bf8-5ba3-11e5-8489-324db9cb43bf.png)

---

My initial suspicion :mag:  is because the list lives :house_with_garden:  within a conditional `dom-if` that somehow I am hitting a race :racehorse: condition when iron-list calcs the height of the container. That said... this seems like not an uncommon usecase :ear: ... is there a "best practice" pattern :memo: for working around this?

Thanks!!! :sparkler: :tiger:

**Comment by blasten** [comment]
@samccone  😑http://jsbin.com/muguwi/edit?html,output I couldn't replicate the issue. Typically, these types of issues are caused when iron-list can't estimate the size of the container because it was hidden.  dom-if will attach a new iron-list when the condition evaluates to `true` and that should trigger `resize`. Can you send me a jsbin that replicates the issue?

**Comment by samccone** [comment]
yep looks like I am still using 1.1.0, unable to upgrade atm... for reasons :cinema: 
Will close, sorry about this one.
